# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MBtddM1hlLOePo_RpMC7E-cMU5lQ6V28
"""

import csv
import os

def cadastro():
    print('---- Cadastro de novo aluno ----')
    nome = input('Digite seu nome: ')

    while True:
        try:
            nota1 = float(input('Digite sua primeira nota: '))
            nota2 = float(input('Digite sua segunda nota: '))
            nota3 = float(input('Digite sua terceira nota: '))
            if 0 <= nota1 <= 10 and 0 <= nota2 <= 10 and 0 <= nota3 <= 10:
                break
            else:
                print('Digite um valor entre 0 e 10')
        except ValueError:
            print('Digite valor numérico válido')

    media = (nota1 + nota2 + nota3) / 3
    media = round(media, 2)

    escrever_cabecalho = not os.path.exists('alunos.csv')

    with open(file='alunos.csv', mode='a', encoding='utf8') as arquivo:
        writer = csv.writer(arquivo)

        if escrever_cabecalho:
            writer.writerow(['Nome', 'Nota 1', 'Nota 2', 'Nota 3', 'Média'])

        writer.writerow([nome, nota1, nota2, nota3, round(media, 2)])

    print('Aluno cadastrado com sucesso!')

def visualizar_alunos():
      if not os.path.exists('alunos.csv'):
        print('\n Nenhum aluno cadastrado')
        return

      with open(file='alunos.csv', mode='r', encoding='utf8') as arquivo:
        reader = csv.reader(arquivo)
        for linha in reader:
            print(linha)

def menu():
  while True:
    print('\n --- Sistema de cadastro de alunos ---')
    print('1 - Cadastrar novo aluno')
    print('2 - Visualizar todos os alunos')
    print('3 - Sair do programa')

    opcao = input('\n  Escolha uma opção\n \n')
    if opcao == '1':
     cadastro()
    elif opcao == '2':
     visualizar_alunos()
    elif opcao == '3':
      print('\n Saindo do programa')
      break
    else:
     print('Opção inválida')

menu()